version: '3.9'
services:

  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "sales"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

  localstack: # LocalStack container
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      # Map the port so you can access the API from the host machine
      - 4566:4566
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./init:/etc/localstack/init/ready.d"