version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql-spring2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - levi_data:/var/lib/mysql

volumes:
  levi_data: