spring.application.name: icecube-ms-core-customer

spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: create
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect

spring.datasource:
  url: jdbc:postgresql://localhost:5432/customer_db
  username: postgres
  password: postgres

spring:
  cloud:
    function:
      definition: customerEventSink
    stream:
      bindings:
        customerEventSink-out-0:
          destination: customer-created-topic
      kafka:
        binder:
          configuration:
            enable.idempotence: true
            acks: all